apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-pvc"
  namespace: "{{ .Values.namespace }}"
  labels:
    experimentId: "{{ .Values.experimentId }}"
    sandboxId: "{{ .Values.sandboxId }}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 'worker-storage-{{.Release.Namespace}}'
  resources:
    requests:
      storage: '{{ .Values.storageSize }}'