version: "3.2"
services:
  r:
    container_name: "biomage-worker-r"
    build:
      context: r/
      target: dev
      args:
        - GITHUB_PAT=${GITHUB_PAT}
    volumes:
      - ./r:/r:cached
      - ./data:/data:cached
    environment:
      - EXPERIMENT_ID=e52b39624588791a7889e39c617f669e
    expose:
      - "4000"
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  pipeline-server:
    container_name: "biomage-pipeline-server"
    build:
      context: pipeline-server/
      target: dev
    volumes:
      - ./pipeline-server:/pipeline-server:cached
    expose:
      - "6969"
    ports:
      - "6969:6969"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  python:
    container_name: "biomage-worker-python"
    build:
      context: python/
      target: dev
    volumes:
      - ./python:/python:cached
      - ./data:/data:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - EXPERIMENT_ID=e52b39624588791a7889e39c617f669e
