apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cleanup-operator
    sandboxId: "{{ .Values.sandboxId }}"
  name: cleanup-operator
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cleanup-operator
      sandboxId: "{{ .Values.sandboxId }}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: cleanup-operator
        sandboxId: "{{ .Values.sandboxId }}"
    spec:
      serviceAccountName: cleanup-operator
      containers:
      - args:
        - --namespace={{.Release.Namespace}}

        # delete successful and failed jobs immediately.
        # this is so failed jobs don't prevent us from running
        # new workers in its place
        - -keep-successful=0
        - -keep-failures=0

        image: quay.io/lwolf/kube-cleanup-operator
        imagePullPolicy: Always
        name: cleanup-operator
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cleanup-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups: ["batch", "extensions"]
  resources:
  - jobs
  verbs:
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cleanup-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cleanup-operator
subjects:
- kind: ServiceAccount
  name: cleanup-operator