apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: can-create-jobs
  namespace: {{ .Release.Namespace }}
  labels:
    sandboxId: "{{ .Values.sandboxId }}"
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "watch", "list", "update", "patch", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]
- apiGroups: ["helm.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["create", "get", "watch", "list", "update", "patch", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: api-can-spawn-workers
  namespace: {{.Release.Namespace}}
  labels:
    sandboxId: "{{ .Values.sandboxId }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: can-create-jobs
subjects:
- kind: ServiceAccount
  name: deployment-runner
  namespace: {{ .Release.Namespace | replace "worker" "api" }}
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: state-machine-runner-group